service: upbeat

image: michaelweiner/upbeat

servers:
  web:
    - 164.90.252.151

proxy:
  ssl: true
  host: up.springcreek.io

registry:
  server: registry.hub.docker.com
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  local: true
  dockerfile: Dockerfile

proxy:
  app_port: 3000

ssh:
  user: <%= ENV['KAMAL_SSH_USERNAME'] %>
  port: <%= ENV['KAMAL_SSH_PORT'] %>
  keys_only: true
  keys: [ "~/.ssh/droplet" ]

