service: upbeat

image: michaelweiner/upbeat

servers:
  web:
    - 159.203.151.191

proxy:
  ssl: true
  hosts: 
    - up.springcreek.io
  app_port: 3000

registry:
  server: registry.hub.docker.com
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  local: true
  dockerfile: Dockerfile

ssh:
  user: <%= ENV['KAMAL_SSH_USERNAME'] %>
  port: <%= ENV['KAMAL_SSH_PORT'] %>
  keys_only: true
  keys: [ "~/.ssh/droplet" ]

